run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly
  allow-parallel-runners: false

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true
